name: Code Generation
on:
  workflow_dispatch:
    inputs:
      run-prefix:
        description: 'Run prefix: {report_id}-{version}'
        required: true

permissions:
  contents: write
  # Also requires Actions permissions (https://github.com/waiyan1612/playground-ghaction/settings/actions) to "Allow GitHub Actions to create and approve pull requests"
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [variant1, variant2]
      max-parallel: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run generator for ${{ matrix.variant }}
        run: python scripts/generator.py > ${{ github.event.inputs['run-prefix'] }}-${{ matrix.variant }}.py

      - name: Upload all variants
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs['run-prefix'] }}-${{ matrix.variant }}
          path: ${{ github.event.inputs['run-prefix'] }}-${{ matrix.variant }}.py
          retention-days: 7

  score:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all variants
        uses: actions/download-artifact@v5
        with:
          path: artifacts/
          merge-multiple: true

      - name: Download test files
        run: python scripts/setup_tests.py

      - name: Run tests and select best candidate
        run: python scripts/run_tests.py

      - name: Upload best variant
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs['run-prefix'] }}
          path: artifacts/${{ github.event.inputs['run-prefix'] }}.py
          retention-days: 7

  commit:
    needs: score
    runs-on: ubuntu-latest
    steps:
      - name: Download best variant
        uses: actions/download-artifact@v5
        with:
          name: ${{ github.event.inputs['run-prefix'] }}
          path: artifacts/

      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        # 271a8d0340265f705b14b6d32b9829c1cb33d45e is the SHA of v7.0.8 
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: artifacts/${{ github.event.inputs['run-prefix'] }}.py
          commit-message: Add ${{ github.event.inputs['run-prefix'] }}.py
          branch: ${{ github.event.inputs['run-prefix'] }}
          branch-suffix: timestamp
          title: Add ${{ github.event.inputs['run-prefix'] }}
          body: Add ${{ github.event.inputs['run-prefix'] }}.py
          draft: false

      - name: Inform the initiator
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
